### ISSUE TITLE
Trouble at script startup during system boot

### ISSUE THREAD

**Issue by WhizASh** [kulvind3r/GamingGaiden#10] opened 2024-05-27 08:27 UTC
**Describe the bug**
I have enables the task scheduling so gaming gaiden would start at boot . but when i system boots the script starts and the powershell is not closing itself up instead it just stays in taskbar and when i close the powershell gaming gaiden also exits .

**To Reproduce**
1. enable the task scheduling using install.bat
2. boot the system

**Expected behavior**
At system boot the powershell start and auto closes and gaming gaiden also stays in background

**Screenshots**
screenshot
![Screenshot 2024-05-27 134700](https://github.com/kulvind3r/GamingGaiden/assets/140056700/7943b482-cc14-451c-9a73-ed73977ab58e)

**Log:**
 2024-05-27T13:40:29 : Cleared log at application boot
2024-05-27T13:40:29 : Executing database setup
2024-05-27T13:40:30 : Database setup complete
2024-05-27T13:40:30 : HWiNFO not detected. Or Gaming Gaiden is already Integrated. Skipping Auto Integration
2024-05-27T13:40:31 : Starting tracker on app boot
2024-05-27T13:40:31 : Resetting Icon and Sensors
2024-05-27T13:40:31 : Started tracker
2024-05-27T13:40:31 : Starting timer to check for Tracking updates
2024-05-27T13:40:31 : Hiding powershell window
2024-05-27T13:40:31 : Starting game detection
2024-05-27T13:40:31 : Running one time garbage collection before app context launch
2024-05-27T13:40:31 : Starting app context

**Comment by kulvind3r** [comment] 2024-05-27 08:33
It is a system tray application, check your system tray. It will be running
there.

There is no GUI window, Powershell window opens and then a tray icon gets
created and the Powershell window closes.

All interaction with application is done using system tray icon menu.

All GUI (games list, graphs etc) is shown in your default web browser when
you click on a action.

**Comment by kulvind3r** [comment] 2024-05-27 12:22
Closing the issue. Not a Bug.

**Closed** 2024-05-27 12:23 UTC

**Comment by WhizASh** [comment] 2024-05-27 18:33
This is screen recording right after system boot


https://github.com/kulvind3r/GamingGaiden/assets/140056700/ee60e898-f610-417c-8a66-26608514fadc

**Comment by kulvind3r** [comment] 2024-05-27 18:37
Why are you closing the Powershell window??

Let the script run completely it will hide the window after it completes
the startup and only the tray icon will remain.

If you close the window then the application will exit.

Let the window run, and reply if it doesn't vanishes even after waiting for
few minutes.

**Comment by kulvind3r** [comment] 2024-05-28 07:05
Not sure why this is happening specifically on your machine...

Does it happen only for the auto start  or does the Powershell window
doesnt close even if you launch using the shortcut in start menu / desktop?

**Comment by kulvind3r** [comment] 2024-05-28 08:08
also can you look at the properties of the shortcut created and share the complete string in the Target box. 

I checked few things and in the scheduled task that is created on my machine, the launch string contains "powershell.exe" and not "powershell". So your machine having just "powershell" is different behavior.

i am on windows 10, it is possible that when install script is run on windows 11, it is creating a scheduled task (and shortcuts) which have "powershell" and not "powershell.exe", leading to a terminal opening which then opens the Powershell window.

**Comment by kulvind3r** [comment] 2024-06-14 12:46
Update: The latest release uses `shell:startup` folder instead of scheduled tasks for auto start and this issue should no longer occur.
