### ISSUE TITLE
Will not track Toontown Rewritten.

### ISSUE THREAD

**Issue by Apocalypse612** [kulvind3r/GamingGaiden#8] opened 2024-05-07 22:42 UTC
**Describe the bug**
The game uses a Launcher.exe to launch. It will not track playtime. Please help.

**Comment by kulvind3r** [comment] 2024-05-08 07:40
You need to find the exe of the game and add that as the game. Don't add the exe of the launcher. 

When you start the game from the launcher, there is a different exe file that is started. You can use Task Manager to identify the exe. 

Start the launcher then open the task manager. Keep both open in front of you. Then when you click launch , a new exe will start in task manager. Right click on that exe and then click open file location, it should take you to where the exe is located.

Add that in Gaming Gaiden as the exe of the game and it will start tracking.

**Comment by Apocalypse612** [comment] 2024-05-08 21:21
Weird, Thanks!

**Comment by kulvind3r** [comment] 2024-05-09 04:48
Not weird at all, this is how game launchers work. They launch a different exe which runs the actual game. You can use this knowledge always with any launcher you encounter in future.

Closing the issue. Not a bug.

**Closed by kulvind3r** 2024-05-09 04:48 UTC
