### ISSUE TITLE
If u have special characters in your username u cant add any games

### ISSUE THREAD

**Issue by ISAKEM** [kulvind3r/GamingGaiden#15] opened 2024-07-17 17:12 UTC
**Describe the bug**
Adding a game fails as it cant find the $env:TEMP directory whenever u have a user that has spaces in the username

**To Reproduce**
Log into any account that has spaces in its username, install GamingGaiden, try adding a game.

**Expected behavior**
What should happen is the "Add Game" window is supposed to show up

**Screenshots**
![image](https://github.com/user-attachments/assets/5e351393-78c0-4b91-8ee4-d4c46f28f486)

**Log:**
Provide error details captured in the *GamingGaiden.log* file
The log doesnt capture this bug

**Additional context**
I tried making it work with spaces but using the "`" escape character does not work nor does double quotations.
In the end I fixed it by running PowerShell as admin and changing the TEMP variable to a new folder I made that doesnt have any spaces by running this command "[Environment]::SetEnvironmentVariable('TEMP', 'C:\Users\TEMP', 'User')"

**Comment by kulvind3r** [comment] 2024-07-17 17:15
Are you using the latest release??

The installation method has changed and now the app is auto installed to a
location which doesn't has this issue.

Check the latest release. And follow the "How to Upgrade from previous
release steps"

**Comment by kulvind3r** [comment] 2024-07-17 17:35
I think I confused it with a different issue which were also caused by
users installing the app in their Home directory with spaces... App was not
loading the modules correctly and exception was very similar

On taking a closer look at the code , it seems like the issue will still be
there with latest release as the temporary files are stored in "$env:TEMP"
path...

Thanks for identifying and reporting... I will see if I can switch to using
System32 Temp directory instead of user specific....

Will fix it one of the upcoming releases.

But do upgrade to latest... Future upgrades will be easier.

**Comment by kulvind3r** [comment] 2024-08-11 04:19
Just for the record , this issue is not caused by spaces in the user name, my own username on my windows machine has a space in the name. I have no issues in using the application.

The issue is caused due to some special characters in usernames with users using different language locales. As is evident in the exception screenshot the user has provided.

**Comment by kulvind3r** [comment] 2024-08-11 11:53
Fixed in [latest release](https://github.com/kulvind3r/GamingGaiden/releases/tag/v2024.8.11). I personally cannot test it though as my locale doesn't have these special characters. 

Either OP can test the release or we will have to wait for someone else to report back if the bug is unfixed. Closing for now.

**Closed by kulvind3r** 2024-08-11 11:53 UTC
