### ISSUE TITLE
Game time being saved as negative values

### ISSUE THREAD

**Issue by thestuckster** [kulvind3r/GamingGaiden#4] opened 2024-03-23 03:02 UTC
# Problem
One of my games was being tracked with negative time values. ex: `-3 hours 20 minutes`. 

# Work Around

Manually removed the `-` from the values in the db tables.

**Comment by kulvind3r** [comment] 2024-03-23 12:46
If the overall time is still adding up after every gaming session and value is increasing, then it might be some formatting problem which is adding `-` sign in front of the time value.

Share your log file, it is in the root folder of application.

Log captures the time recorded in the current gaming session before adding it to the already recorded time and updating the final total. 

However if you have restarted the application then the log file is cleaned completely and started fresh. So i can only debug if the log still has entries for the game that is giving you problem.

**Comment by thestuckster** [comment] 2024-03-24 18:08
Unfortunately I restarted my PC so the log file is lost forever :cry:

**Comment by kulvind3r** [comment] 2024-03-26 05:58
I am closing the issue in that case.

I cannot reproduce it on my end and since it happened only for one game for you, there must be some edge case that is going wrong.

We will need an example to identify the edge case. 

Feel free to open a new issue if you see this problem again and please capture the log immediately then. :-)

**Closed by kulvind3r** 2024-03-26 05:58 UTC
